[[plugins]]
  package = "netlify-plugin-minify-html"
    [plugins.inputs]
      contexts = ["production"] # only minify in production
    # https://github.com/kangax/html-minifier#options-quick-reference
    [plugins.inputs.minifierOptions]
      removeComments = true
      minifyJS = true
      collapseWhitespace = true

[[edge_functions]]
  function = "og"
  path = "/og"
